name: event-workflows

on:
  push:
  pull_request:
    types: [opened,reopened]
  workflow_dispatch:
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
          - name: event name
            run: echo "event name is ${{ github.event_name}}"
