name: 14 - Working with artifacts
on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        description: version of the node
        type: choice
        options:
          - 20.x
          - 21.x
          - 22.x
        default: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package.lock.json') }}" >> $GITHUB_OUTPUT
        id: cache-key
      - name: Download cached dependencies
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
            path: 13-caching/react-app/node_modules
            key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 13-caching/react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
        run:
          working-directory: 13-caching/react-app
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build
      - name: showcase folder
        run: |
         ls -R
      - name: deploying
        run: echo "deploying"